### ISSUE TITLE
Team Rachel Griffith Code Review

### ISSUE THREAD

**Issue by hippogriff04** [lizchoi0918/EEP153-Project3-4-Spring2023#1]
Hi! 
The analysis looks good overall! And the graphs are labeled with clear axes and titles!
Some graphs have overlapping parts between curves and indicators on the right. It may be better to put the indicators on the right next to the curves to make the graphs look better! 
And there are many runtime errors indicator 'cannot divide by zero'. There might be some minor mistakes within the data or calculations. 
Thank you!

**Comment by lizchoi0918** [comment]
Hi, thank you for the input! 
The runtime error indicating cannot divide by zero is due to some data manipulation that we have done on our google sheets that are more coherent with the rest of the data. We have replace nan into 0 after the initial clean up to make useful analysis going forward.
