### ISSUE TITLE
Team T.W. Schultz Code Review

### ISSUE THREAD

**Issue by saaaallYao** [lizchoi0918/EEP153-Project3-4-Spring2023#2]
Overall the code is very neat and well-structured. I leave some of my comments here:
1. Some of the plots are hard to read. For the Engel curves, there are too many lines overlapping and the legend blocks the view. I think setting a bigger size for the plot may help solve this problem.
2. Also it would better to show only some of foods or nutrients on the plot to have a better view and emphasis on them

**Comment by lizchoi0918** [comment]
Hi, thank you for the input!
For general analysis, we wanted to look at the general trend and if there are any particular food product that stands out in the engel curve. However, we also implemented individual food items if we wanted to look at a specific product. The code is not too hard to manipulate and we have made necessary adjustments as we conducted our data analysis.
